Feat: Add GPT-4o model (with caveats)
b1ek/hey pull request #6
Opened 2024-08-04 01:31 UTC by Ahmad-A0

This PR adds the `gpt-4o-mini` model, which can be set with the string `GPT4OMini` in the config.

```toml
model = "GPT4OMini"
```

I also made a change to disable the vqd caching and retrieval functionality. It seems DuckDuckGo have changed something on their backend, which causes errors with the newer model. This change doesn't seem to effect any of the model outputs, I may just be misunderstanding something so please do take a look.

```rust
    pub fn get_last_vqd<'a, T: From<&'a String>>(self: &'a Self) -> Option<T> {
        None
        /*if self.last_vqd_time - (chrono::Local::now().timestamp_millis() as u64) < 60000 {
            Some((&self.last_vqd).into())
        } else {
            None
        } */
    }
```

2024-08-05 03:19 UTC, b1ek commented
whys it closed? looks good enough to me

2024-08-05 03:20 UTC, b1ek requested changes
i will merge it manually when its ok

2024-08-05 05:55 UTC, Ahmad-A0 commented on src/cache.rs
> +        /*if self.last_vqd_time - (chrono::Local::now().timestamp_millis() as u64) < 60000 {
No problem.

2024-08-06 09:32 UTC, b1ek approved these changes

2024-08-06 09:34 UTC, merged

2024-09-23 05:34 UTC, pokegamer5547 commented
Hello, i'm having this issue when using gpt4omini model (tho it works but only sometimes) i'm using latest dev and compiled it myself (i'm on android)
![Screenshot_20240923-110212_Termux_1](https://github.com/user-attachments/assets/7e0bb5ce-8606-4699-8e21-343e7992d0be)

2024-09-23 08:18 UTC, b1ek commented
@pokegamer5547 it has something to do with their API. if you have been abusing it then you are hitting the rate limit, but if you havent then it needs to be looked into

you should like open an issue for it

2024-09-23 08:27 UTC, pokegamer5547 commented
> @pokegamer5547 it has something to do with their API. if you have been abusing it then you are hitting the rate limit, but if you havent then it needs to be looked into
> 
> you should like open an issue for it

It's first time i used this and even on first try i had this issue. And i'm able to access on browser just time. And yes you're right, i'll open new issue for it. Even now after few hours and from other phone too on different network i'm having same issue.